[package]
name = "ycsb"
version = "0.1.0"
edition = "2024"

[features]
default = []
serde = ["dep:serde"]

[dependencies]
bon = "3.6"
serde = { version = "1.0", features = ["derive"], optional = true }
rand = "0.9"
rapidhash = "1.4"
